import Image from "next/image";

// Icons
import { RiComputerFill } from "react-icons/ri";

export const Tecnologias = () => {
    return (
        <div id="tecnologias" className="flex flex-col justify-center container mx-auto px-4 md:pt-20 xl:w-1/2 xl:px-2 xl:pt-16 xl:h-[calc(100vh-rem)]">
            <h1 className="text-slate-100 text-2xl font-bold mt-6 mb-1 md:text-4xl"><RiComputerFill className='inline-block mb-1 mr-1' /> Tecnologías</h1>
            <section className="flex items-center gap-x-2 mb-4">
                <span className="text-red-500 text-lg font-semibold bg-slate-800 px-1 rounded-lg">Básico</span>
                <span className="text-amber-500 text-lg font-semibold bg-slate-800 px-1 rounded-lg">Intermedio</span>
                <span className="text-green-600 text-lg font-semibold bg-slate-800 px-1 rounded-lg">Avanzado</span>
            </section>
            <section className="shadow rounded-lg bg-slate-700 pb-5 flex justify-center items-center border-slate-600 border">
                <ul className="grid grid-cols-2 gap-y-3 gap-x-3 pl-4 pt-5 md:grid-cols-4 md:gap-y-10 md:pl-10">
                    <li className="flex text-amber-500 font-semibold items-center justify-start "><Image src="/images/logos/HTML5.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40}/><span className="bg-slate-800 p-1 rounded-lg">HTML5</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/CSS.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">CSS</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/JavaScript.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300 rounded-lg" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">JavaScript</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/React.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">React</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Node.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Node.js</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Next.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Next.js</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Postgre.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">PostgreSQL</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Mysql.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300 rounded-lg" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">MySQL</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Git.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Git</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Github.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">GitHub</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Prisma.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Prisma</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Sequelize.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Sequelize</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Tailwind.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Tailwind</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/MUI.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Material UI</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Bootstrap.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Bootstrap</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Express.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Express</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Vite.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Vite</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Jsonwebtoken.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">JWT</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/VisualStudioCode.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">VS Code</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/VS2022.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">VS 2022</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/SQLserver.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">SQL Server</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Figma.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Figma</span></li>
                    <li className="flex text-amber-500 font-semibold items-center justify-start"><Image src="/images/logos/Handlebars.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Handlebars</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/Python.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Python</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/Typescript.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300 rounded-lg" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">TypeScript</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/EntityFramework.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300 rounded-lg" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Entity Framework</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/ASP.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">ASP.Core</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/PS.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300 rounded-sm" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Photoshop</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/NETcore.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">.NET Core</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/C.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">C#</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/Angular.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Angular</span></li>
                    <li className="flex text-red-500 font-semibold items-center justify-start"><Image src="/images/logos/Django.png" alt="foto" className="mx-2 hover:scale-150 transition-transform duration-300" width={40} height={40} /><span className="bg-slate-800 p-1 rounded-lg">Django</span></li>
                </ul>
            </section>
        </div>
    )
};